import { NgModule } from '@angular/core';

import {MatButtonModule, 
        MatTabsModule,
        MatToolbarModule, 
        MatSidenavModule, 
        MatMenuModule,
        MatCardModule,
        MatTableModule,
        MatSortModule,
        MatExpansionModule,
        MatSelectModule,
        MatDatepickerModule,
        MatNativeDateModule,
        MatInputModule,
        MatSnackBarModule,
        MatTooltipModule,
        MatBottomSheetModule,
        MatProgressSpinnerModule,
        MatStepperModule,
        MatIconModule,
        MatCheckboxModule,
        MatGridListModule,
        MatAutocompleteModule,
        MatDividerModule
        } from '@angular/material';


@NgModule({
        imports: [MatButtonModule, 
                MatTabsModule,
                MatToolbarModule, 
                MatSidenavModule, 
                MatMenuModule,
                MatCardModule,
                MatTableModule,
                MatSortModule,
                MatExpansionModule,
                MatSelectModule,
                MatDatepickerModule,
                MatNativeDateModule,
                MatInputModule,
                MatSnackBarModule,
                MatTooltipModule,
                MatBottomSheetModule,
                MatProgressSpinnerModule,
                MatStepperModule,
                MatIconModule,
                MatCheckboxModule,
                MatGridListModule,
                MatAutocompleteModule,
                MatDividerModule],
        exports:[MatButtonModule, 
                MatTabsModule,
                MatToolbarModule, 
                MatSidenavModule, 
                MatMenuModule,
                MatCardModule,
                MatTableModule,
                MatSortModule,
                MatExpansionModule,
                MatSelectModule,
                MatDatepickerModule,
                MatNativeDateModule,
                MatInputModule,
                MatSnackBarModule,
                MatTooltipModule,
                MatBottomSheetModule,
                MatProgressSpinnerModule,
                MatStepperModule,
                MatIconModule,
                MatCheckboxModule,
                MatGridListModule,
                MatAutocompleteModule,
                MatDividerModule]

})

export class MyMaterialModule {}